<?php

class ZipcodeTableSeeder extends Seeder {

	public function run()
	{
		$zipcode = array(
				['ZIP_code'=>'1000', 'city'=> 'Ljubljana'],
['ZIP_code'=>'1001', 'city'=> 'Ljubljana - P.P.'],
['ZIP_code'=>'1210', 'city'=> 'Ljubljana - Šentvid'],
['ZIP_code'=>'1211', 'city'=> 'Ljubljana - Šmartno'],
['ZIP_code'=>'1215', 'city'=> 'Medvode'],
['ZIP_code'=>'1216', 'city'=> 'Smlednik'],
['ZIP_code'=>'1217', 'city'=> 'Vodice'],
['ZIP_code'=>'1218', 'city'=> 'Komenda'],
['ZIP_code'=>'1219', 'city'=> 'Laze v Tuhinju'],
['ZIP_code'=>'1221', 'city'=> 'Motnik'],
['ZIP_code'=>'1222', 'city'=> 'Trojane'],
['ZIP_code'=>'1223', 'city'=> 'Blagovica'],
['ZIP_code'=>'1225', 'city'=> 'Lukovica'],
['ZIP_code'=>'1230', 'city'=> 'Domžale'],
['ZIP_code'=>'1231', 'city'=> 'Ljubljana - Črnuče'],
['ZIP_code'=>'1233', 'city'=> 'Dob'],
['ZIP_code'=>'1234', 'city'=> 'Mengeš'],
['ZIP_code'=>'1235', 'city'=> 'Radomlje'],
['ZIP_code'=>'1236', 'city'=> 'Trzin'],
['ZIP_code'=>'1241', 'city'=> 'Kamnik'],
['ZIP_code'=>'1242', 'city'=> 'Stahovica'],
['ZIP_code'=>'1251', 'city'=> 'Moravče'],
['ZIP_code'=>'1252', 'city'=> 'Vače'],
['ZIP_code'=>'1260', 'city'=> 'Ljubljana - Polje'],
['ZIP_code'=>'1261', 'city'=> 'Ljubljana - Dobrunje'],
['ZIP_code'=>'1262', 'city'=> 'Dol pri Ljubljani'],
['ZIP_code'=>'1270', 'city'=> 'Litija'],
['ZIP_code'=>'1272', 'city'=> 'Polšnik'],
['ZIP_code'=>'1273', 'city'=> 'Dole pri Litiji'],
['ZIP_code'=>'1274', 'city'=> 'Gabrovka'],
['ZIP_code'=>'1275', 'city'=> 'Šmartno pri Litiji'],
['ZIP_code'=>'1276', 'city'=> 'Primskovo '],
['ZIP_code'=>'1281', 'city'=> 'Kresnice'],
['ZIP_code'=>'1282', 'city'=> 'Sava'],
['ZIP_code'=>'1290', 'city'=> 'Grosuplje'],
['ZIP_code'=>'1291', 'city'=> 'Škofljica'],
['ZIP_code'=>'1292', 'city'=> 'Ig'],
['ZIP_code'=>'1293', 'city'=> 'Šmarje - Sap'],
['ZIP_code'=>'1294', 'city'=> 'Višnja Gora'],
['ZIP_code'=>'1295', 'city'=> 'Ivančna Gorica'],
['ZIP_code'=>'1296', 'city'=> 'Šentvid pri Stični'],
['ZIP_code'=>'1301', 'city'=> 'Krka'],
['ZIP_code'=>'1303', 'city'=> 'Zagradec'],
['ZIP_code'=>'1310', 'city'=> 'Ribnica'],
['ZIP_code'=>'1311', 'city'=> 'Turjak'],
['ZIP_code'=>'1312', 'city'=> 'Videm - Dobrepolje'],
['ZIP_code'=>'1313', 'city'=> 'Struge'],
['ZIP_code'=>'1314', 'city'=> 'Rob'],
['ZIP_code'=>'1315', 'city'=> 'Velike Lašče'],
['ZIP_code'=>'1316', 'city'=> 'Ortnek'],
['ZIP_code'=>'1317', 'city'=> 'Sodražica'],
['ZIP_code'=>'1318', 'city'=> 'Loški Potok'],
['ZIP_code'=>'1319', 'city'=> 'Draga'],
['ZIP_code'=>'1330', 'city'=> 'Kočevje'],
['ZIP_code'=>'1331', 'city'=> 'Dolenja vas'],
['ZIP_code'=>'1332', 'city'=> 'Stara Cerkev'],
['ZIP_code'=>'1336', 'city'=> 'Kostel'],
['ZIP_code'=>'1337', 'city'=> 'Osilnica'],
['ZIP_code'=>'1338', 'city'=> 'Kočevska Reka'],
['ZIP_code'=>'1351', 'city'=> 'Brezovica pri Ljubljani'],
['ZIP_code'=>'1352', 'city'=> 'Preserje'],
['ZIP_code'=>'1353', 'city'=> 'Borovnica'],
['ZIP_code'=>'1354', 'city'=> 'Horjul'],
['ZIP_code'=>'1355', 'city'=> 'Polhov Gradec'],
['ZIP_code'=>'1356', 'city'=> 'Dobrova'],
['ZIP_code'=>'1357', 'city'=> 'Notranje Gorice'],
['ZIP_code'=>'1358', 'city'=> 'Log pri Brezovici'],
['ZIP_code'=>'1360', 'city'=> 'Vrhnika'],
['ZIP_code'=>'1370', 'city'=> 'Logatec'],
['ZIP_code'=>'1371', 'city'=> 'Logatec'],
['ZIP_code'=>'1372', 'city'=> 'Hotedršica'],
['ZIP_code'=>'1373', 'city'=> 'Rovte'],
['ZIP_code'=>'1380', 'city'=> 'Cerknica'],
['ZIP_code'=>'1381', 'city'=> 'Rakek'],
['ZIP_code'=>'1382', 'city'=> 'Begunje pri Cerknici'],
['ZIP_code'=>'1384', 'city'=> 'Grahovo'],
['ZIP_code'=>'1385', 'city'=> 'Nova vas'],
['ZIP_code'=>'1386', 'city'=> 'Stari trg pri Ložu'],
['ZIP_code'=>'1410', 'city'=> 'Zagorje ob Savi'],
['ZIP_code'=>'1411', 'city'=> 'Izlake'],
['ZIP_code'=>'1412', 'city'=> 'Kisovec'],
['ZIP_code'=>'1413', 'city'=> 'Čemšenik'],
['ZIP_code'=>'1414', 'city'=> 'Podkum'],
['ZIP_code'=>'1420', 'city'=> 'Trbovlje'],
['ZIP_code'=>'1423', 'city'=> 'Dobovec'],
['ZIP_code'=>'1430', 'city'=> 'Hrastnik'],
['ZIP_code'=>'1431', 'city'=> 'Dol pri Hrastniku'],
['ZIP_code'=>'1432', 'city'=> 'Zidani Most'],
['ZIP_code'=>'1433', 'city'=> 'Radeče'],
['ZIP_code'=>'1434', 'city'=> 'Loka pri Zidanem Mostu'],
['ZIP_code'=>'2000', 'city'=> 'Maribor '],
['ZIP_code'=>'2001', 'city'=> 'Maribor - P.P.'],
['ZIP_code'=>'2201', 'city'=> 'Zgornja Kungota'],
['ZIP_code'=>'2204', 'city'=> 'Miklavž na Dravskem polju'],
['ZIP_code'=>'2205', 'city'=> 'Starše'],
['ZIP_code'=>'2206', 'city'=> 'Marjeta na Dravskem polju'],
['ZIP_code'=>'2208', 'city'=> 'Pohorje'],
['ZIP_code'=>'2211', 'city'=> 'Pesnica pri Mariboru'],
['ZIP_code'=>'2212', 'city'=> 'Šentilj v Slovenskih goricah'],
['ZIP_code'=>'2213', 'city'=> 'Zgornja Velka'],
['ZIP_code'=>'2214', 'city'=> 'Sladki Vrh'],
['ZIP_code'=>'2215', 'city'=> 'Ceršak'],
['ZIP_code'=>'2221', 'city'=> 'Jarenina'],
['ZIP_code'=>'2222', 'city'=> 'Jakobski Dol'],
['ZIP_code'=>'2223', 'city'=> 'Jurovski Dol'],
['ZIP_code'=>'2229', 'city'=> 'Malečnik'],
['ZIP_code'=>'2230', 'city'=> 'Lenart v Slovenskih goricah'],
['ZIP_code'=>'2231', 'city'=> 'Pernica'],
['ZIP_code'=>'2232', 'city'=> 'Voličina'],
['ZIP_code'=>'2233', 'city'=> 'Sv. Ana v Slovenskih goricah'],
['ZIP_code'=>'2234', 'city'=> 'Benedikt'],
['ZIP_code'=>'2235', 'city'=> 'Sv. Trojica v Slovenskih goricah'],
['ZIP_code'=>'2236', 'city'=> 'Cerkvenjak'],
['ZIP_code'=>'2241', 'city'=> 'Spodnji Duplek'],
['ZIP_code'=>'2242', 'city'=> 'Zgornja Korena'],
['ZIP_code'=>'2250', 'city'=> 'Ptuj'],
['ZIP_code'=>'2252', 'city'=> 'Dornava'],
['ZIP_code'=>'2253', 'city'=> 'Destrnik'],
['ZIP_code'=>'2254', 'city'=> 'Trnovska vas'],
['ZIP_code'=>'2255', 'city'=> 'Vitomarci'],
['ZIP_code'=>'2256', 'city'=> 'Juršinc'],
['ZIP_code'=>'2257', 'city'=> 'Polenšak'],
['ZIP_code'=>'2258', 'city'=> 'Sveti Tomaž'],
['ZIP_code'=>'2259', 'city'=> 'Ivanjkovci'],
['ZIP_code'=>'2270', 'city'=> 'Ormož'],
['ZIP_code'=>'2272', 'city'=> 'Gorišnica'],
['ZIP_code'=>'2273', 'city'=> 'Podgorci'],
['ZIP_code'=>'2274', 'city'=> 'Velika Nedelja'],
['ZIP_code'=>'2275', 'city'=> 'Miklavž pri Ormožu'],
['ZIP_code'=>'2276', 'city'=> 'Kog'],
['ZIP_code'=>'2277', 'city'=> 'Središče ob Dravi'],
['ZIP_code'=>'2281', 'city'=> 'Markovci'],
['ZIP_code'=>'2282', 'city'=> 'Cirkulane'],
['ZIP_code'=>'2283', 'city'=> 'Zavrč'],
['ZIP_code'=>'2284', 'city'=> 'Videm pri Ptuju'],
['ZIP_code'=>'2285', 'city'=> 'Zgornji Leskovec'],
['ZIP_code'=>'2286', 'city'=> 'Podlehnik'],
['ZIP_code'=>'2287', 'city'=> 'Žetale'],
['ZIP_code'=>'2288', 'city'=> 'Hajdina'],
['ZIP_code'=>'2289', 'city'=> 'Stoperce'],
['ZIP_code'=>'2310', 'city'=> 'Slovenska Bistrica'],
['ZIP_code'=>'2311', 'city'=> 'Hoče'],
['ZIP_code'=>'2312', 'city'=> 'Orehova vas'],
['ZIP_code'=>'2313', 'city'=> 'Fram'],
['ZIP_code'=>'2314', 'city'=> 'Zgornja Polskava'],
['ZIP_code'=>'2315', 'city'=> 'Šmartno na Pohorju'],
['ZIP_code'=>'2316', 'city'=> 'Zgornja Ložnica'],
['ZIP_code'=>'2317', 'city'=> 'Oplotnica'],
['ZIP_code'=>'2318', 'city'=> 'Laporje'],
['ZIP_code'=>'2319', 'city'=> 'Poljčane'],
['ZIP_code'=>'2321', 'city'=> 'Makole'],
['ZIP_code'=>'2322', 'city'=> 'Majšperk'],
['ZIP_code'=>'2323', 'city'=> 'Ptujska Gora'],
['ZIP_code'=>'2324', 'city'=> 'Lovrenc na Dravskem polju'],
['ZIP_code'=>'2325', 'city'=> 'Kidričevo'],
['ZIP_code'=>'2326', 'city'=> 'Cirkovce'],
['ZIP_code'=>'2327', 'city'=> 'Rače'],
['ZIP_code'=>'2331', 'city'=> 'Pragersko'],
['ZIP_code'=>'2341', 'city'=> 'Limbuš'],
['ZIP_code'=>'2342', 'city'=> 'Ruše'],
['ZIP_code'=>'2343', 'city'=> 'Fala'],
['ZIP_code'=>'2344', 'city'=> 'Lovrenc na Pohorju'],
['ZIP_code'=>'2345', 'city'=> 'Bistrica ob Dravi'],
['ZIP_code'=>'2351', 'city'=> 'Kamnica'],
['ZIP_code'=>'2352', 'city'=> 'Selnica ob Dravi'],
['ZIP_code'=>'2353', 'city'=> 'Sveti Duh na Ostrem Vrhu'],
['ZIP_code'=>'2354', 'city'=> 'Bresternica'],
['ZIP_code'=>'2360', 'city'=> 'Radlje ob Dravi'],
['ZIP_code'=>'2361', 'city'=> 'Ožbalt'],
['ZIP_code'=>'2362', 'city'=> 'Kapla'],
['ZIP_code'=>'2363', 'city'=> 'Podvelka'],
['ZIP_code'=>'2364', 'city'=> 'Ribnica na Pohorju'],
['ZIP_code'=>'2365', 'city'=> 'Vuhred'],
['ZIP_code'=>'2366', 'city'=> 'Muta'],
['ZIP_code'=>'2367', 'city'=> 'Vuzenica'],
['ZIP_code'=>'2370', 'city'=> 'Dravograd'],
['ZIP_code'=>'2371', 'city'=> 'Trbonje'],
['ZIP_code'=>'2372', 'city'=> 'Libeliče'],
['ZIP_code'=>'2373', 'city'=> 'Šentjanž pri Dravogradu'],
['ZIP_code'=>'2380', 'city'=> 'Slovenj Gradec'],
['ZIP_code'=>'2381', 'city'=> 'Podgorje pri Slovenj Gradcu'],
['ZIP_code'=>'2382', 'city'=> 'Mislinja'],
['ZIP_code'=>'2383', 'city'=> 'Šmartno pri Slovenj Gradcu'],
['ZIP_code'=>'2390', 'city'=> 'Ravne na Koroškem'],
['ZIP_code'=>'2391', 'city'=> 'Prevalje'],
['ZIP_code'=>'2392', 'city'=> 'Mežica'],
['ZIP_code'=>'2393', 'city'=> 'Črna na Koroškem'],
['ZIP_code'=>'2394', 'city'=> 'Kotlje'],
['ZIP_code'=>'3000', 'city'=> 'Celje '],
['ZIP_code'=>'3001', 'city'=> 'Celje - P.P.'],
['ZIP_code'=>'3201', 'city'=> 'Šmartno v Rožni dolini'],
['ZIP_code'=>'3202', 'city'=> 'Ljubečna'],
['ZIP_code'=>'3203', 'city'=> 'Nova Cerkev'],
['ZIP_code'=>'3205', 'city'=> 'Vitanje'],
['ZIP_code'=>'3206', 'city'=> 'Stranice'],
['ZIP_code'=>'3210', 'city'=> 'Slovenske Konjice'],
['ZIP_code'=>'3211', 'city'=> 'Škofja vas'],
['ZIP_code'=>'3212', 'city'=> 'Vojnik'],
['ZIP_code'=>'3213', 'city'=> 'Frankolovo'],
['ZIP_code'=>'3214', 'city'=> 'Zreče'],
['ZIP_code'=>'3215', 'city'=> 'Loče'],
['ZIP_code'=>'3220', 'city'=> 'Štore'],
['ZIP_code'=>'3221', 'city'=> 'Teharje'],
['ZIP_code'=>'3222', 'city'=> 'Dramlje'],
['ZIP_code'=>'3223', 'city'=> 'Loka pri Žusmu'],
['ZIP_code'=>'3224', 'city'=> 'Dobje pri Planini'],
['ZIP_code'=>'3225', 'city'=> 'Planina pri Sevnici'],
['ZIP_code'=>'3230', 'city'=> 'Šentjur'],
['ZIP_code'=>'3231', 'city'=> 'Grobelno'],
['ZIP_code'=>'3232', 'city'=> 'Ponikva'],
['ZIP_code'=>'3233', 'city'=> 'Kalobje'],
['ZIP_code'=>'3240', 'city'=> 'Šmarje pri Jelšah'],
['ZIP_code'=>'3241', 'city'=> 'Podplat'],
['ZIP_code'=>'3250', 'city'=> 'Rogaška Slatina'],
['ZIP_code'=>'3252', 'city'=> 'Rogatec'],
['ZIP_code'=>'3253', 'city'=> 'Pristava pri Mestinju'],
['ZIP_code'=>'3254', 'city'=> 'Podčetrtek'],
['ZIP_code'=>'3255', 'city'=> 'Buče'],
['ZIP_code'=>'3256', 'city'=> 'Bistrica ob Sotli'],
['ZIP_code'=>'3257', 'city'=> 'Podsreda'],
['ZIP_code'=>'3260', 'city'=> 'Kozje'],
['ZIP_code'=>'3261', 'city'=> 'Lesično'],
['ZIP_code'=>'3262', 'city'=> 'Prevorje'],
['ZIP_code'=>'3263', 'city'=> 'Gorica pri Slivnici'],
['ZIP_code'=>'3264', 'city'=> 'Sveti Štefan'],
['ZIP_code'=>'3270', 'city'=> 'Laško'],
['ZIP_code'=>'3271', 'city'=> 'Šentrupert'],
['ZIP_code'=>'3272', 'city'=> 'Rimske Toplice'],
['ZIP_code'=>'3273', 'city'=> 'Jurklošter'],
['ZIP_code'=>'3301', 'city'=> 'Petrovče'],
['ZIP_code'=>'3302', 'city'=> 'Griže'],
['ZIP_code'=>'3303', 'city'=> 'Gomilsko'],
['ZIP_code'=>'3304', 'city'=> 'Tabor'],
['ZIP_code'=>'3305', 'city'=> 'Vransko'],
['ZIP_code'=>'3310', 'city'=> 'Žalec'],
['ZIP_code'=>'3311', 'city'=> 'Šempeter v Savinjski dolini'],
['ZIP_code'=>'3312', 'city'=> 'Prebold'],
['ZIP_code'=>'3313', 'city'=> 'Polzela'],
['ZIP_code'=>'3314', 'city'=> 'Braslovče'],
['ZIP_code'=>'3320', 'city'=> 'Velenje '],
['ZIP_code'=>'3322', 'city'=> 'Velenje - P.P.'],
['ZIP_code'=>'3325', 'city'=> 'Šoštanj'],
['ZIP_code'=>'3326', 'city'=> 'Topolšica'],
['ZIP_code'=>'3327', 'city'=> 'Šmartno ob Paki'],
['ZIP_code'=>'3330', 'city'=> 'Mozirje'],
['ZIP_code'=>'3331', 'city'=> 'Nazarje'],
['ZIP_code'=>'3332', 'city'=> 'Rečica ob Savinji'],
['ZIP_code'=>'3333', 'city'=> 'Ljubno ob Savinji'],
['ZIP_code'=>'3334', 'city'=> 'Luče'],
['ZIP_code'=>'3335', 'city'=> 'Solčava'],
['ZIP_code'=>'3341', 'city'=> 'Šmartno ob Dreti'],
['ZIP_code'=>'3342', 'city'=> 'Gornji Grad'],
['ZIP_code'=>'4000', 'city'=> 'Kranj '],
['ZIP_code'=>'4001', 'city'=> 'Kranj – P.P.'],
['ZIP_code'=>'4201', 'city'=> 'Zgornja Besnica'],
['ZIP_code'=>'4202', 'city'=> 'Naklo'],
['ZIP_code'=>'4203', 'city'=> 'Duplje'],
['ZIP_code'=>'4204', 'city'=> 'Golnik'],
['ZIP_code'=>'4205', 'city'=> 'Preddvor'],
['ZIP_code'=>'4206', 'city'=> 'Zgornje Jezersko'],
['ZIP_code'=>'4207', 'city'=> 'Cerklje na Gorenjskem'],
['ZIP_code'=>'4208', 'city'=> 'Šenčur'],
['ZIP_code'=>'4209', 'city'=> 'Žabnica'],
['ZIP_code'=>'4210', 'city'=> 'Brnik - Aerodrom'],
['ZIP_code'=>'4211', 'city'=> 'Mavčiče'],
['ZIP_code'=>'4212', 'city'=> 'Visoko'],
['ZIP_code'=>'4220', 'city'=> 'Škofja Loka'],
['ZIP_code'=>'4223', 'city'=> 'Poljane nad Škofjo Loko'],
['ZIP_code'=>'4224', 'city'=> 'Gorenja vas'],
['ZIP_code'=>'4225', 'city'=> 'Sovodenj'],
['ZIP_code'=>'4226', 'city'=> 'Žiri'],
['ZIP_code'=>'4227', 'city'=> 'Selca'],
['ZIP_code'=>'4228', 'city'=> 'Železniki'],
['ZIP_code'=>'4229', 'city'=> 'Sorica'],
['ZIP_code'=>'4240', 'city'=> 'Radovljica'],
['ZIP_code'=>'4243', 'city'=> 'Brezje'],
['ZIP_code'=>'4244', 'city'=> 'Podnart'],
['ZIP_code'=>'4245', 'city'=> 'Kropa'],
['ZIP_code'=>'4246', 'city'=> 'Kamna Gorica'],
['ZIP_code'=>'4247', 'city'=> 'Zgornje Gorje'],
['ZIP_code'=>'4248', 'city'=> 'Lesce'],
['ZIP_code'=>'4260', 'city'=> 'Bled'],
['ZIP_code'=>'4263', 'city'=> 'Bohinjska Bela'],
['ZIP_code'=>'4264', 'city'=> 'Bohinjska Bistrica'],
['ZIP_code'=>'4265', 'city'=> 'Bohinjsko jezero'],
['ZIP_code'=>'4267', 'city'=> 'Srednja vas v Bohinju'],
['ZIP_code'=>'4270', 'city'=> 'Jesenice'],
['ZIP_code'=>'4273', 'city'=> 'Blejska Dobrava'],
['ZIP_code'=>'4274', 'city'=> 'Žirovnica'],
['ZIP_code'=>'4275', 'city'=> 'Begunje na Gorenjskem'],
['ZIP_code'=>'4276', 'city'=> 'Hrušica'],
['ZIP_code'=>'4280', 'city'=> 'Kranjska Gora'],
['ZIP_code'=>'4281', 'city'=> 'Mojstrana'],
['ZIP_code'=>'4282', 'city'=> 'Gozd Martuljek'],
['ZIP_code'=>'4283', 'city'=> 'Rateče - Planica'],
['ZIP_code'=>'4290', 'city'=> 'Tržič'],
['ZIP_code'=>'4294', 'city'=> 'Križe'],
['ZIP_code'=>'5000', 'city'=> 'Nova Gorica '],
['ZIP_code'=>'5001', 'city'=> 'Nova Gorica - P.P.'],
['ZIP_code'=>'3204', 'city'=> 'Dobrna'],
['ZIP_code'=>'5210', 'city'=> 'Deskle'],
['ZIP_code'=>'5211', 'city'=> 'Kojsko'],
['ZIP_code'=>'5212', 'city'=> 'Dobrovo v Brdih'],
['ZIP_code'=>'5213', 'city'=> 'Kanal'],
['ZIP_code'=>'5214', 'city'=> 'Kal nad Kanalom'],
['ZIP_code'=>'5215', 'city'=> 'Ročinj'],
['ZIP_code'=>'5216', 'city'=> 'Most na Soči'],
['ZIP_code'=>'5220', 'city'=> 'Tolmin'],
['ZIP_code'=>'5222', 'city'=> 'Kobarid'],
['ZIP_code'=>'5223', 'city'=> 'Breginj'],
['ZIP_code'=>'5224', 'city'=> 'Srpenica'],
['ZIP_code'=>'5230', 'city'=> 'Bovec'],
['ZIP_code'=>'5231', 'city'=> 'Log pod Mangartom'],
['ZIP_code'=>'5232', 'city'=> 'Soča'],
['ZIP_code'=>'5242', 'city'=> 'Grahovo ob Bači'],
['ZIP_code'=>'5243', 'city'=> 'Podbrdo'],
['ZIP_code'=>'5250', 'city'=> 'Solkan'],
['ZIP_code'=>'5251', 'city'=> 'Grgar'],
['ZIP_code'=>'5252', 'city'=> 'Trnovo pri Gorici'],
['ZIP_code'=>'5253', 'city'=> 'Čepovan'],
['ZIP_code'=>'5261', 'city'=> 'Šempas'],
['ZIP_code'=>'5262', 'city'=> 'Črniče'],
['ZIP_code'=>'5263', 'city'=> 'Dobravlje'],
['ZIP_code'=>'5270', 'city'=> 'Ajdovščina'],
['ZIP_code'=>'5271', 'city'=> 'Vipava'],
['ZIP_code'=>'5272', 'city'=> 'Podnanos'],
['ZIP_code'=>'5273', 'city'=> 'Col'],
['ZIP_code'=>'5274', 'city'=> 'Črni Vrh nad Idrijo'],
['ZIP_code'=>'5275', 'city'=> 'Godovič'],
['ZIP_code'=>'5280', 'city'=> 'Idrija'],
['ZIP_code'=>'5281', 'city'=> 'Spodnja Idrija'],
['ZIP_code'=>'5282', 'city'=> 'Cerkno'],
['ZIP_code'=>'5283', 'city'=> 'Slap ob Idrijci'],
['ZIP_code'=>'5290', 'city'=> 'Šempeter pri Gorici'],
['ZIP_code'=>'5291', 'city'=> 'Miren'],
['ZIP_code'=>'5292', 'city'=> 'Renče'],
['ZIP_code'=>'5293', 'city'=> 'Volčja Draga'],
['ZIP_code'=>'5294', 'city'=> 'Dornberk'],
['ZIP_code'=>'5295', 'city'=> 'Branik'],
['ZIP_code'=>'5296', 'city'=> 'Kostanjevica na Krasu'],
['ZIP_code'=>'5297', 'city'=> 'Prvačina'],
['ZIP_code'=>'6000', 'city'=> 'Koper/Capodistria '],
['ZIP_code'=>'6001', 'city'=> 'Koper/Capodistria – P.P.'],
['ZIP_code'=>'6210', 'city'=> 'Sežana'],
['ZIP_code'=>'6215', 'city'=> 'Divača'],
['ZIP_code'=>'6216', 'city'=> 'Podgorje'],
['ZIP_code'=>'6217', 'city'=> 'Vremski Britof'],
['ZIP_code'=>'6219', 'city'=> 'Lokev'],
['ZIP_code'=>'6221', 'city'=> 'Dutovlje'],
['ZIP_code'=>'6222', 'city'=> 'Štanjel'],
['ZIP_code'=>'6223', 'city'=> 'Komen'],
['ZIP_code'=>'6224', 'city'=> 'Senožeče'],
['ZIP_code'=>'6225', 'city'=> 'Hruševje'],
['ZIP_code'=>'6230', 'city'=> 'Postojna'],
['ZIP_code'=>'6232', 'city'=> 'Planina'],
['ZIP_code'=>'6240', 'city'=> 'Kozina'],
['ZIP_code'=>'6242', 'city'=> 'Materija'],
['ZIP_code'=>'6243', 'city'=> 'Obrov'],
['ZIP_code'=>'6244', 'city'=> 'Podgrad'],
['ZIP_code'=>'6250', 'city'=> 'Ilirska Bistrica'],
['ZIP_code'=>'6251', 'city'=> 'Ilirska Bistrica-Trnovo'],
['ZIP_code'=>'6253', 'city'=> 'Knežak'],
['ZIP_code'=>'6254', 'city'=> 'Jelšane'],
['ZIP_code'=>'6255', 'city'=> 'Prem'],
['ZIP_code'=>'6256', 'city'=> 'Košana'],
['ZIP_code'=>'6257', 'city'=> 'Pivka'],
['ZIP_code'=>'6258', 'city'=> 'Prestranek'],
['ZIP_code'=>'6271', 'city'=> 'Dekani'],
['ZIP_code'=>'6272', 'city'=> 'Gračišče'],
['ZIP_code'=>'6273', 'city'=> 'Marezige'],
['ZIP_code'=>'6274', 'city'=> 'Šmarje'],
['ZIP_code'=>'6275', 'city'=> 'Črni Kal'],
['ZIP_code'=>'6276', 'city'=> 'Pobegi'],
['ZIP_code'=>'6280', 'city'=> 'Ankaran/Ancarano'],
['ZIP_code'=>'6281', 'city'=> 'Škofije'],
['ZIP_code'=>'6310', 'city'=> 'Izola/Isola'],
['ZIP_code'=>'6320', 'city'=> 'Portorož/Portorose'],
['ZIP_code'=>'6330', 'city'=> 'Piran/Pirano'],
['ZIP_code'=>'6333', 'city'=> 'Sečovlje/Sicciole'],
['ZIP_code'=>'8000', 'city'=> 'Novo mesto'],
['ZIP_code'=>'8001', 'city'=> 'Novo mesto - P.P.'],
['ZIP_code'=>'8210', 'city'=> 'Trebnje'],
['ZIP_code'=>'8211', 'city'=> 'Dobrnič'],
['ZIP_code'=>'8212', 'city'=> 'Velika Loka'],
['ZIP_code'=>'8213', 'city'=> 'Veliki Gaber'],
['ZIP_code'=>'8216', 'city'=> 'Mirna Peč'],
['ZIP_code'=>'8220', 'city'=> 'Šmarješke Toplice'],
['ZIP_code'=>'8222', 'city'=> 'Otočec'],
['ZIP_code'=>'8230', 'city'=> 'Mokronog'],
['ZIP_code'=>'8231', 'city'=> 'Trebelno '],
['ZIP_code'=>'8232', 'city'=> 'Šentrupert'],
['ZIP_code'=>'8233', 'city'=> 'Mirna'],
['ZIP_code'=>'8250', 'city'=> 'Brežice'],
['ZIP_code'=>'8251', 'city'=> 'Čatež ob Savi'],
['ZIP_code'=>'8253', 'city'=> 'Artiče'],
['ZIP_code'=>'8254', 'city'=> 'Globoko'],
['ZIP_code'=>'8255', 'city'=> 'Pišece'],
['ZIP_code'=>'8256', 'city'=> 'Sromlje '],
['ZIP_code'=>'8257', 'city'=> 'Dobova'],
['ZIP_code'=>'8258', 'city'=> 'Kapele'],
['ZIP_code'=>'8259', 'city'=> 'Bizeljsko'],
['ZIP_code'=>'8261', 'city'=> 'Jesenice na Dolenjskem'],
['ZIP_code'=>'8262', 'city'=> 'Krška vas'],
['ZIP_code'=>'8263', 'city'=> 'Cerklje ob Krki'],
['ZIP_code'=>'8270', 'city'=> 'Krško'],
['ZIP_code'=>'8272', 'city'=> 'Zdole '],
['ZIP_code'=>'8273', 'city'=> 'Leskovec pri Krškem'],
['ZIP_code'=>'8274', 'city'=> 'Raka'],
['ZIP_code'=>'8275', 'city'=> 'Škocjan'],
['ZIP_code'=>'8276', 'city'=> 'Bučka '],
['ZIP_code'=>'8280', 'city'=> 'Brestanica'],
['ZIP_code'=>'8281', 'city'=> 'Senovo'],
['ZIP_code'=>'8282', 'city'=> 'Koprivnica'],
['ZIP_code'=>'8283', 'city'=> 'Blanca'],
['ZIP_code'=>'8290', 'city'=> 'Sevnica'],
['ZIP_code'=>'8292', 'city'=> 'Zabukovje '],
['ZIP_code'=>'8293', 'city'=> 'Studenec'],
['ZIP_code'=>'8294', 'city'=> 'Boštanj'],
['ZIP_code'=>'8295', 'city'=> 'Tržišče'],
['ZIP_code'=>'8296', 'city'=> 'Krmelj'],
['ZIP_code'=>'8297', 'city'=> 'Šentjanž'],
['ZIP_code'=>'8310', 'city'=> 'Šentjernej'],
['ZIP_code'=>'8311', 'city'=> 'Kostanjevica na Krki'],
['ZIP_code'=>'8312', 'city'=> 'Podbočje'],
['ZIP_code'=>'8321', 'city'=> 'Brusnice'],
['ZIP_code'=>'8322', 'city'=> 'Stopiče'],
['ZIP_code'=>'8323', 'city'=> 'Uršna sela'],
['ZIP_code'=>'8330', 'city'=> 'Metlika'],
['ZIP_code'=>'8331', 'city'=> 'Suhor'],
['ZIP_code'=>'8332', 'city'=> 'Gradac'],
['ZIP_code'=>'8333', 'city'=> 'Semič'],
['ZIP_code'=>'8340', 'city'=> 'Črnomelj'],
['ZIP_code'=>'8341', 'city'=> 'Adlešiči'],
['ZIP_code'=>'8342', 'city'=> 'Stari trg ob Kolpi'],
['ZIP_code'=>'8343', 'city'=> 'Dragatuš'],
['ZIP_code'=>'8344', 'city'=> 'Vinica'],
['ZIP_code'=>'8350', 'city'=> 'Dolenjske Toplice'],
['ZIP_code'=>'8351', 'city'=> 'Straža'],
['ZIP_code'=>'8360', 'city'=> 'Žužemberk'],
['ZIP_code'=>'8361', 'city'=> 'Dvor'],
['ZIP_code'=>'8362', 'city'=> 'Hinje'],
['ZIP_code'=>'9000', 'city'=> 'Murska Sobota '],
['ZIP_code'=>'9001', 'city'=> 'Murska Sobota - P.P.'],
['ZIP_code'=>'9201', 'city'=> 'Puconci'],
['ZIP_code'=>'9202', 'city'=> 'Mačkovci'],
['ZIP_code'=>'9203', 'city'=> 'Petrovci'],
['ZIP_code'=>'9204', 'city'=> 'Šalovci'],
['ZIP_code'=>'9205', 'city'=> 'Hodoš/Hodos'],
['ZIP_code'=>'9206', 'city'=> 'Križevci'],
['ZIP_code'=>'9207', 'city'=> 'Prosenjakovci/Partosfalva'],
['ZIP_code'=>'9208', 'city'=> 'Fokovci'],
['ZIP_code'=>'9220', 'city'=> 'Lendava/Lendva'],
['ZIP_code'=>'9221', 'city'=> 'Martjanci'],
['ZIP_code'=>'9222', 'city'=> 'Bogojina'],
['ZIP_code'=>'9223', 'city'=> 'Dobrovnik/Dobronak'],
['ZIP_code'=>'9224', 'city'=> 'Turnišče'],
['ZIP_code'=>'9225', 'city'=> 'Velika Polana '],
['ZIP_code'=>'9226', 'city'=> 'Moravske Toplice'],
['ZIP_code'=>'9227', 'city'=> 'Kobilje'],
['ZIP_code'=>'9231', 'city'=> 'Beltinci'],
['ZIP_code'=>'9232', 'city'=> 'Črenšovci'],
['ZIP_code'=>'9233', 'city'=> 'Odranci'],
['ZIP_code'=>'9240', 'city'=> 'Ljutomer'],
['ZIP_code'=>'9241', 'city'=> 'Veržej'],
['ZIP_code'=>'9242', 'city'=> 'Križevci pri Ljutomeru'],
['ZIP_code'=>'9243', 'city'=> 'Mala Nedelja'],
['ZIP_code'=>'9244', 'city'=> 'Sveti Jurij ob Ščavnici'],
['ZIP_code'=>'9245', 'city'=> 'Spodnji Ivanjci'],
['ZIP_code'=>'9250', 'city'=> 'Gornja Radgona'],
['ZIP_code'=>'9251', 'city'=> 'Tišina'],
['ZIP_code'=>'9252', 'city'=> 'Radenci'],
['ZIP_code'=>'9253', 'city'=> 'Apače'],
['ZIP_code'=>'9261', 'city'=> 'Cankova'],
['ZIP_code'=>'9262', 'city'=> 'Rogašovci'],
['ZIP_code'=>'9263', 'city'=> 'Kuzma'],
['ZIP_code'=>'9264', 'city'=> 'Grad'],
['ZIP_code'=>'9265', 'city'=> 'Bodonci']
		);

		// Uncomment the below to run the seeder
		// DB::table('zipcode')->insert($zipcode);
	}

}
